title: Pippo
description: >-
  Personal homepage of Philipp 
lang: en-US
timezone: Europe/Berlin
image: ''
repo: ''
mode: dark
author:
  name: Pippo
  bio: >-
    ðŸ‡©ðŸ‡ªðŸ‡®ðŸ‡¹ðŸ‡ªðŸ‡º</br>
    I work in Data & Analytics at <a href="https://www.project-a.com"
    target="_blank" rel="noopener">Project A</a>.
  username: pippowie
  github: pippowie
  twitter: pippowie
  linkedin: philipp-wiedemann
  avatar: assets/img/avatar
url: 'https://pippowie.github.io/'
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
